### ISSUE TITLE
Update option --token in cml-pr helppage

### ISSUE THREAD

**Issue by Crazy-Tony** [iterative/cml.dev#109]
The helppage of cml-pr describes the option --token as a personal access token, but project access tokens can also be used for that. So i recommend to update the helppage by adding information about project access tokens.

**Comment by casperdcl** [comment]
The GitLab section under https://cml.dev/doc/self-hosted-runners#personal-access-token does indeed mention project access tokens. With #70 will hopefully make it clearer :)

**Comment by Crazy-Tony** [comment]
Yes that's right. People like me, who are taking a look first into the helppage if something doesn't work as expected, the helppage  seems quite misleading.
