### ISSUE TITLE
Educational Course Connect

### ISSUE THREAD

**Issue by jendefig** [iterative/cml.dev#132]
With the new educational course coming out at the end of the quarter, we need to determine how people will access it from our websites.

Each website will access the same school: Iterative Tools School.

[Here is information on how their domains work](https://support.learnworlds.com/support/solutions/articles/12000080095-general-overview-custom-domains#What-is-a-custom-domain?). Let me know how you think it's best to proceed!

@julieg18 @rogermparent @yalozhkin

**Comment by jendefig** [comment]
@shcheklein The course is hosted at LearnWorlds.  Working on getting it set up...

A subdomain works for me.  I like learn.iterative.ai

**Comment by shcheklein** [comment]
@jendefig could you invite me as an admin? I can setup a subdomain, I hope it can be quick.

**Comment by jendefig** [comment]
> @jendefig could you invite me as an admin? I can setup a subdomain, I hope it can be quick.

@shcheklein I just changed the login info and updated 1 Password so it's a social@iterative.ai in the Social section.

**Comment by shcheklein** [comment]
I've proceeded and requested the change to learn.iterative.ai via CNAME record. Please @mike0sv @jendefig let me know if you see any problems.

**Comment by casperdcl** [comment]
Where do we report issues with the website btw? I can see a bunch of little bugs.

**Comment by jendefig** [comment]
@mnrozhkov  See above.  Wrong Mike was tagged.  

@casperdcl If you are talking about with the LearnWorlds site, and the bugs are beyond layout, current set up, and entries, feel free and figure that out, because I have no idea.  If the bugs are related to the fact that I've only just started putting stuff in and it is in no way ready for review, please don't waste your time.  Spend it taking a good headshot. 😉

**Comment by mnrozhkov** [comment]
@jendefig thanks! looks good, I like learn.iterative.ai! Could you give me an admin access to be able to check and start to use it?

**Comment by jendefig** [comment]
> @jendefig thanks! looks good, I like learn.iterative.ai! Could you give me an admin access to be able to check and start to use it?

You can get the access in 1 Password @mnrozhkov

**Comment by rogermparent** [comment]
Does this issue track the fact that cml.dev doesn't have any links to learn.iterative.ai? It seems https://github.com/iterative/cml.dev/pull/197 was closed because we decided the course doesn't have enough CML content to warrant connecting it to cml.dev now. Should we close this ticket until that time comes?

**Comment by jendefig** [comment]
Yes.  While I think it makes sense that all tools lead there to get people learning, it is true that we plan for more CML content in the next course.  We can implement the connection then and close this issue.
