### ISSUE TITLE
Need a social image on CML.dev

### ISSUE THREAD

**Issue by jendefig** [iterative/cml.dev#141]
Just realized we are missing a social image on CML.dev.  I can take care of it, but not sure where it lives and need appropriate sizing.
@casperdcl @rogermparent @julieg18 

![image](https://user-images.githubusercontent.com/34289199/140402767-abcf1856-559c-48c5-ab8f-510da580dcf3.png)

**Comment by julieg18** [comment]
Weird, it appears to be working for me:

![image](https://user-images.githubusercontent.com/43496356/140411165-b63debba-356a-40f7-a8b5-38830356aebf.png)

Is it still broken on your side?

**Comment by jendefig** [comment]
@julieg18 No!  It shows up correctly now!  I wonder why there was a delay? 🤔 Guess we can close.

**Comment by julieg18** [comment]
Yes! I'll look into reasons for image delays.
