### ISSUE TITLE
Docs: self-hosted runners -> Personal Access Token -> App upgrade

### ISSUE THREAD

**Issue by mikolajpabiszczak** [iterative/cml.dev#150]
In the docs concerning self-hosted runners, section Personal Access Token / App (https://cml.dev/doc/self-hosted-runners#app). The following is written:

>  Use either:
> - a personal access token with the repo scope, or
> - a GitHub App with Repository permissions / Administration write permissions (for repository-level runners), or Organization permissions / Self-hosted runners write permissions (for organization-level runners).

The second case is not described correctly enough. The app needs more permissions - depending which commands will be used (`pr`, `send-comment`, `send-github-check`) - so, e.g., access to write Pull requests needs to be granted and so on...

**Comment by casperdcl** [comment]
Thanks, https://cml.dev/doc/self-hosted-runners?tab=GitHub#app is updated now :pray:
