### ISSUE TITLE
tabs: nesting

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#158]
Nested tabs (`<tab title="Container"><tab title="sub"></tab></tab>` would be nice. Not sure of how to show them in URLs though. Probably `/?tab=Container-sub`?

**Comment by julieg18** [comment]
> Nested tabs (<tab title="Container"><tab title="sub"></tab></tab> would be nice. Not sure of how to show them in URLs though. Probably /?tab=Container-sub?

This is doable! As for naming, maybe `?tab=container&tab=sub-container`? It could be lengthy if we had more than two layers, but I can't think of doc examples that would need more than two nested layers of tabs 🤔

**Comment by casperdcl** [comment]
The problem with `?tab=Container&tab=sub` is ambiguity between 2 top-level tabs versus nested tabs.

(Related example: from an `#id` perspective, concatenation with hyphens is fully supported, but 2nd level `#id`s aren't)

**Comment by julieg18** [comment]
Are we ok with how this looks styling wise? 

![image](https://user-images.githubusercontent.com/43496356/144858022-2f6d873e-5d0d-4ae9-887a-bffb5cfaf8b9.png)

I'm not sure how we could improve it 🤔

**Comment by casperdcl** [comment]
#137 would avoid the problem of alpha transparency addition taking us to multiple shades of grey.

I count at least 2 puns in that sentence.

Fine with sorting #137 later though - it looks ok for now.
