### ISSUE TITLE
Update docs content to use Prismjs syntax highlighting and ref: auto-link options

### ISSUE THREAD

**Issue by yathomasi** [iterative/cml.dev#239]
With #233, the following features were added

1. #157 
2. #187 

Now, we need to update content similar to dvc.org to use them (jump to https://github.com/iterative/cml.dev/issues/239#issuecomment-1227495713).

cc: @iterative/docs

**Comment by jorgeorpinel** [comment]
> the following features were added

Can you be specific about which highlighters exist or how to enable them, as well as auto-linking? We'll want to document this at some point anyway (maybe in the docs engine repo README + contrib guides).

**Comment by yathomasi** [comment]
Existing highlighters:

1. `dvc`
    * parses on line basis (accepts `$ `as first character which is skipped while copying)
    * highlights
        * `dvc` commands
        * `git` commands
        * `bash` commands
2. `dvctable`
    * parses on row/line basis
    * highlights
      * `white|neutral`
      * `yellow|metric`
      *  `blue|param`
      *  `violet|dep`
3. `usage`
   * highlights
     * `dvc` commands
     *  `cml` commands (**_addition_**)
     * `usage` commands `usage|positional arguments|optional arguments`
     * `args` highlights the arguments in `[--arg]` pattern (inside square bracket with double dashes) (_**auto-linking**_)
4. `cml` (**_addition_**)
    * parses on line basis (accepts `$ `as first character which is skipped while copying)
    * highlights
        * `cml` commands
        * `git` commands
        * `bash` commands

Usage: 
````
```dvc | dvctable| usage| cml
respective content
```
````

**Comment by casperdcl** [comment]
Er... Can

- `cml` be an alias of `dvc`
- both of the above highlight all of our tools (`dvc/cml/mlem/...`)

**Comment by jorgeorpinel** [comment]
> Can cml be an alias of dvc?

See discussion in https://github.com/iterative/mlem.ai/issues/59 🙂

**Comment by casperdcl** [comment]
Yes basically would like [this](https://github.com/iterative/gatsby-theme-iterative/pull/12#issuecomment-1132493265) rather than [this](https://github.com/iterative/cml.dev/issues/239#issuecomment-1130091708)

**Comment by jorgeorpinel** [comment]
Is this still outstanding @yathomasi ? Thanks

**Comment by rogermparent** [comment]
Seems like the `cli` highlighter that's already in closes this issue.

**Comment by jorgeorpinel** [comment]
> Can `cml` be an alias of `dvc`?

Note that the highlighter name is now `cli` @casperdcl . I think both `dvc` and `cml` will be aliases of that but I recommend we use `cli` going fwd.

Do you want to keep this issue open to update existing content and use the highlighters more?

**Comment by rogermparent** [comment]
Unless something has changed, we only have `dvc` as an alias but we're encouraging moving to full `cli`, we've already mass replaced instances of ` ```dvc` in a few repos.
