### ISSUE TITLE
fenced codeblocks

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#247]
Use more features from https://dvc.org/doc/contributing/docs, e.g. fenced code block lang `usage` & `dvc`/`cml`.

**Comment by jorgeorpinel** [comment]
I think these should be in the engine now? Cc @iterative/websites

**Comment by rogermparent** [comment]
Yep, they're in the engine, and I see examples of ` ```cli` and ` ```usage` throughout the cml.dev repo. I think this issue is handled any way you look at it.
