### ISSUE TITLE
examples: add --pr

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#331]
- [ ] https://github.com/iterative/cml_base_case/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aexample
- [ ] https://github.com/iterative/cml_dvc_case/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aexample
- [ ] https://github.com/iterative/cml_cloud_case/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aexample
- [ ] https://github.com/iterative/cml-runner-base-case/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aexample
- [ ] https://github.com/iterative/cml_tensorboard_case/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aexample

see https://github.com/iterative/cml/issues/1139

**Comment by jorgeorpinel** [comment]
Looks like the first check box is duplicated. Also (unrelated), do the **cml_base_case** and **cml_cloud_case** repos need the `example` topic?

**Comment by jorgeorpinel** [comment]
> see iterative/cml#1139

 So is the context here the following? Just wanted to clarify this ticket, thanks.

> the --pr flag is now mandatory for CML reports to show up in PRs...
> update docs & examples

**Comment by casperdcl** [comment]
Replaced by #415
