### ISSUE TITLE
Bitbucket GPU case review 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml.dev#367]
Right now we are just only advertising that GPU is not supported. 
@0x2b3bfa0 suggested to remove the case or display a big not supported.

I prefer to show the same case warning that the GPU is not supported. At some point BB would fix it and we would just only remove the warning

**Comment by casperdcl** [comment]
would prefer a TPI GPU BB demo /CC @dacbd (as per https://github.com/iterative/cml.dev/pull/362#discussion_r1014527509)

**Comment by 0x2b3bfa0** [comment]
As per https://github.com/iterative/cml.dev/pull/362#discussion_r1016044837, @dacbd is preparing https://github.com/iterative/cml-examples-dev/pull/24 in the meantime.

**Comment by casperdcl** [comment]
Fixed by https://github.com/iterative/cml-examples-dev/pull/24; follow-ups tracked in #349
