### ISSUE TITLE
Link results in 404 page not found

### ISSUE THREAD

**Issue by LisaZeller** [iterative/cml.dev#377]
In the gitlab.md last chapter 'Final Solution' the provided link [iterative.ai/cml-base-case](https://gitlab.com/iterative.ai/cml-base-case) does not work. 

Also the link in the first chapter 'Get Started with CML on GitLab' [example project repository](https://gitlab.com/iterative.ai/example_cml) is not working.

Is there no more sample project on Gitlab?

**Comment by jorgeorpinel** [comment]
@LisaZeller thanks for the report. Would it be possible to link to the pages where you see the broken links for now?

Cc @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
@0x2b3bfa0's blunder, fixed with https://github.com/iterative/cml-examples-dev/commit/0af9bf020d0ab3eb285a3359e0137fb4d1586e4b too late, will be solved as soon as an administrator addresses [p1668558046997539](https://iterativeai.slack.com/archives/C01R00PPQ1L/p1668558046997539).

**Comment by 0x2b3bfa0** [comment]
@LisaZeller, sorry for the inconvenience. In the meantime you can use https://gitlab.com/iterative-test/cml-example-minimal instead of https://gitlab.com/iterative.ai/cml-base-case.

**Comment by 0x2b3bfa0** [comment]
Solved with [3427766853](https://github.com/iterative/cml-examples-dev/actions/runs/3427766853)
