### ISSUE TITLE
How to stop this auto-hyperlinking?

### ISSUE THREAD

**Issue by rogermparent** [iterative/cml.dev#424]
> @iterative/websites any idea how to stop `cml runner launch ... --cloud=aws --labels=cml-gpu` from auto-hyperlinking to `/doc/ref/runner#--cloud`?

_Originally posted by @casperdcl in https://github.com/iterative/cml.dev/pull/417#discussion_r1046469804_
      
Seems like our args auto-linker's flag reading functionality includes instances where more than one flag is given. While minor, this doesn't make much sense so we should probably restrict the linking to when only one argument is present.

**Comment by jorgeorpinel** [comment]
It's based on this file https://github.com/iterative/gatsby-theme-iterative/blob/main/packages/gatsby-theme-iterative/config/prismjs/cml-commands.js but the logic (not sure where) is not very strict and tries to find something to link to within the corresponding cmd ref. I've raised this in the past: https://github.com/iterative/dvc.org/issues/1614
