### ISSUE TITLE
Add `engines` key to `package.json`

### ISSUE THREAD

**Issue by julieg18** [iterative/cml.dev#48]
Example:
```
"engines": {
    "node": "14.x"
  }
```

**Comment by julieg18** [comment]
Currently our `engines` key looks like this:
```json
"engines": {
    "node": "<=15.x"
  },
```
@rogermparent, is this good to keep or should we have it match dvc.org which has `14.x`?

**Comment by rogermparent** [comment]
May as well move it down for consistency and the fact that 14 is LTS while 15 is not. Ideally we move to 16 after the upgrade is done.

**Comment by julieg18** [comment]
Whoops, was looking at the wrong package.json! dvc.org does actually have `<=15.x` as its `engines.node` key. And placing a `14.x` key breaks the CircleCI tests (#65) . Do we want to keep both cml.dev and dvc.org with a `<=15.x` or change it to something like `<=14.x`?

**Comment by rogermparent** [comment]
No worries! I'm pretty sure `<=14.x` will solve the issue since the problem is CircleCI running Node 12, though maybe it'd be better to upgrade CCI to 14- not sure how feasible that is since I don't touch CCI often.
