### ISSUE TITLE
linters on GH Codespaces

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#87]
Apparently `npm up && yarn format-all && yarn pretty-quick` changes files in Codespaces (Node v14) but not locally (Node v14).

- reported at https://github.com/iterative/cml.dev/pull/81#discussion_r690791533

**Comment by 0x2b3bfa0** [comment]
Yes, not sure if I am doing something wrong, but it seems to modify some quotation marks. 🤔

**Comment by dacbd** [comment]
Is this still a thing? also do we care about `<=14.x`? shouldn't 16.x at the oldest be the concern?
