### ISSUE TITLE
prod site not building

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#94]
None of the recent merged PRs are live (e.g. #89, #90, #91, #92 versus https://cml.dev/doc/self-hosted-runners)

**Comment by rogermparent** [comment]
Seems like automatic deploys weren't enabled on Heroku, I just turned them on and did a manual deploy of master

**Comment by rogermparent** [comment]
Just verified the self hosted runners doc has new content, thanks for the catch @casperdcl!
